### PR TITLE
Removed globals and made into class

### PR DESCRIPTION
**Pull request by amastis**
- cleaned up some bugs
- cleaned up duplicate code
- added class
- improved menu handling
- able to add as many bots as you want

Todos:
- add load save game -- not being used currently
-  user input validation 
- fix view_stats + reset_stats

### CODE REVIEW

**Comment by JordanLeich** [comment]
@amastis Thanks a lot man really appreciate it. If you got discord, add me Rampage#0841 I would like to chat with you.

**Comment by amastis** [comment]
@JordanLeich  Your discord needs to have 4 numbers at the end not 3. Will add you.

**Comment by JordanLeich** [comment]
@amastis sorry about that, Rampage#0841

**Comment by JordanLeich** [comment]
The numbers at the end are 0841, idk why it won't let me paste it on GitHub

**Pull request merged**
